/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BoardElement.Character.CharacterFactory;
import BoardElement.Character.CharacterListingFactory;
import BoardElement.Character.Concrete.CharacterBasic;
import BoardElement.Character.ICharacter;
import BoardElement.Character.ICharacterListing;
import BoardElement.Tools.Concrete.Skill;
import BoardElement.Tools.Concrete.Weapon;
import BoardElement.Tools.ITool;
import BoardElement.Tools.IToolListing;
import BoardElement.Tools.ToolFactory;
import BoardElement.Tools.ToolListingFactory;
import Media.IMediaElement;
import Media.MediaElementFactory;
import Media.MediaListingFactory;
import Patterns.IBuilder;
import Views.MainSelectCreationView;

/**
 *
 * @author Marvin Armando
 */
public class Main extends javax.swing.JFrame {
    public CharacterListingFactory characterListingFactory = new CharacterListingFactory();
    public CharacterFactory characterFactory = CharacterFactory.getInstance();
    
    public ToolListingFactory toolListingFactory = new ToolListingFactory();
    public ToolFactory toolFactory = new ToolFactory();
    
    public MediaListingFactory mediaListingFactory  = new MediaListingFactory();
    public MediaElementFactory mediaElementFactory = new MediaElementFactory();
    
    public ICharacterListing characterListing;
    public boolean loadTemplates = true;
    
    public IToolListing tools = toolListingFactory.getToolListing(0);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        loadTemplates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton1)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton1)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainSelectCreationView mainSelectCreationView = new MainSelectCreationView(characterFactory.getCharacters(),tools);
        mainSelectCreationView.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void loadTemplates(){
        
        IMediaElement imageCharacterLvl0= mediaElementFactory.getMedia(0);
        imageCharacterLvl0.setPath("src\\Images\\Character\\magicLvl1.png");
        IMediaElement imageCharacterLvl1 = mediaElementFactory.getMedia(0);
        imageCharacterLvl1.setPath("src\\Images\\Character\\magicLvl2.png");
        IMediaElement imageCharacterLvl2 = mediaElementFactory.getMedia(0);
        imageCharacterLvl2.setPath("src\\Images\\Character\\magicLvl3.png");
        IMediaElement imageCharacterLvl3 = mediaElementFactory.getMedia(0);
        imageCharacterLvl3.setPath("src\\Images\\Character\\magicLvl4.png");
        

        IMediaElement imageSkillPreview= mediaElementFactory.getMedia(0);
        imageSkillPreview.setPath("src\\Images\\Character\\Skill\\ball\\ballPREVIEW.png");
        IMediaElement imageSkillLvl0= mediaElementFactory.getMedia(0);
        imageSkillLvl0.setPath("src\\Images\\Character\\Skill\\ball\\ballLevel1.png");
        IMediaElement imageSkillLvl1= mediaElementFactory.getMedia(0);
        imageSkillLvl1.setPath("src\\Images\\Character\\Skill\\ball\\ballLevel2.png");

        IMediaElement imageWeaponPreview= mediaElementFactory.getMedia(0);
        imageWeaponPreview.setPath("src\\Images\\Character\\Weapon\\Stick\\stickPREVIEW.png");
        IMediaElement imageWeaponLvl0= mediaElementFactory.getMedia(0);
        imageWeaponLvl0.setPath("src\\Images\\Character\\Weapon\\Stick\\stickLevel1.png");
        IMediaElement imageWeaponLvl1= mediaElementFactory.getMedia(0);
        imageWeaponLvl1.setPath("src\\Images\\Character\\Weapon\\Stick\\stickLevel2.png");
        
        IToolListing toolListingCharacter = toolListingFactory.getToolListing(0);
        
        
        
        Skill.SkillBuilder skillBuilder = new Skill.SkillBuilder();
        skillBuilder.setName("Skill").setDecrementableLife(10).setDefaultLife(10).setLevel(10).setMinCharacterLevelReq(10)
                .setMinPlayerLevelReq(10).setReach(10).setSimpleUseDecrement(10).setType(1)
                .addMedia(imageSkillPreview).addMedia(imageSkillLvl0).addMedia(imageSkillLvl1);
        ITool toolSkill = skillBuilder.build();
        toolListingCharacter.addTool(toolSkill);
        tools.addTool(toolSkill);
        toolFactory.addPrototype(toolSkill);
        //System.out.println("Size de tools" + toolSkill.getMediaListing().getMedia().size());
        
        
        Weapon.WeaponBuilder weaponBuilder = new Weapon.WeaponBuilder();
        weaponBuilder.setDecrementableLife(10).setDefaultLife(10).setLevel(10).setMinCharacterLevelReq(10)
                .setMinPlayerLevelReq(10).setName("Weapon").setReach(10).setSimpleUseDecrement(10)
                .setType(0).addMedia(imageWeaponPreview).addMedia(imageWeaponLvl0).addMedia(imageWeaponLvl1);
        ITool toolWeapon = weaponBuilder.build();
        toolListingCharacter.addTool(toolWeapon);
        tools.addTool(toolWeapon);
        toolFactory.addPrototype(toolWeapon);
        System.out.println("La lista de tools tiene:"+tools.getSize());
        
        characterListing = characterListingFactory.getCharacterListing(0);
        CharacterBasic.CharacterBasicBuilder characterBasicBuilder = new CharacterBasic.CharacterBasicBuilder();
        characterBasicBuilder.setDecrementableLife(10).setDefaultLife(10).setFields(10).setHitsPerUnit(10)
                .setLevel(10).setMinPlayerLevelReq(10).setName("Barbaro").addImage(imageCharacterLvl0)
                .addImage(imageCharacterLvl1).addImage(imageCharacterLvl2).addImage(imageCharacterLvl3)
                .addTool(toolSkill).addTool(toolWeapon);
        ICharacter character = characterBasicBuilder.build();
        characterListing.addCharacter(character);
        characterFactory.addPrototype(character);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
