/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import BoardElement.Character.CharacterFactory;
import BoardElement.Character.CharacterListingFactory;
import BoardElement.Character.ICharacter;
import BoardElement.Character.ICharacterListing;
import BoardElement.Tools.Concrete.Skill;
import BoardElement.Tools.Concrete.Weapon;
import BoardElement.Tools.ITool;
import BoardElement.Tools.IToolListing;
import BoardElement.Tools.ToolArray;
import BoardElement.Tools.ToolFactory;
import BoardElement.Tools.ToolListingFactory;
import Media.Concrete.ImageArray;
import Media.IMediaElement;
import Media.IMediaListing;
import Media.MediaElementFactory;
import Media.MediaListingFactory;
import Patterns.IBuilder;
import java.awt.Image;
import java.io.File;

/**
 *
 * @author Marvin Armando
 */
public  class MainSelectCreationView extends javax.swing.JFrame {
    
    public CharacterListingFactory characterListingFactory = new CharacterListingFactory();
    public CharacterFactory characterFactory = new CharacterFactory();
    
    public ToolListingFactory toolListingFactory = new ToolListingFactory();
    public ToolFactory toolFactory = new ToolFactory();
    
    public MediaListingFactory mediaListingFactory  = new MediaListingFactory();
    public MediaElementFactory mediaElementFactory = new MediaElementFactory();
    

    /**
     * Creates new form MainCharacterView
     */
    public MainSelectCreationView() {
        initComponents();
        loadTemplates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        templatesButton = new javax.swing.JButton();
        newCharacterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        templatesButton.setText("Templates");
        templatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templatesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(templatesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, 60));

        newCharacterButton.setText("NewCharacter");
        newCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCharacterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newCharacterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 240, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void templatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templatesButtonActionPerformed
        // TODO add your handling code here:
        
        TemplatesCharacterView templatesCharacterView = new  TemplatesCharacterView(this.character);
        templatesCharacterView.setVisible(true);
        
    }//GEN-LAST:event_templatesButtonActionPerformed

    private void newCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCharacterButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newCharacterButtonActionPerformed

    public void loadTemplates(){
        
        IMediaListing imagesCharacter = mediaListingFactory.getMediaListing(0);
        IMediaElement imageCharacterLvl0= mediaElementFactory.getTool(0);
        imageCharacterLvl0.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\magicLvl1.png");
        IMediaElement imageCharacterLvl1 = mediaElementFactory.getTool(0);
        imageCharacterLvl1.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\magicLvl2.png");
        IMediaElement imageCharacterLvl2 = mediaElementFactory.getTool(0);
        imageCharacterLvl2.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\magicLvl3.png");
        IMediaElement imageCharacterLvl3 = mediaElementFactory.getTool(0);
        imageCharacterLvl3.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\magicLvl4.png");
        imagesCharacter.loadMedia(imageCharacterLvl0);
        imagesCharacter.loadMedia(imageCharacterLvl1);
        imagesCharacter.loadMedia(imageCharacterLvl2);
        imagesCharacter.loadMedia(imageCharacterLvl3);
        
        
        IMediaListing imagesToolSkill = mediaListingFactory.getMediaListing(0);
        IMediaElement imageSkillPreview= mediaElementFactory.getTool(0);
        imageSkillPreview.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\Skill\\ball\\ballPREVIEW.png");
        IMediaElement imageSkillLvl0= mediaElementFactory.getTool(0);
        imageSkillLvl0.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\Skill\\ball\\ballLevel1.png");
        IMediaElement imageSkillLvl1= mediaElementFactory.getTool(0);
        imageSkillLvl1.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\Skill\\ball\\ballLevel2.png");
        imagesToolSkill.loadMedia(imageSkillPreview);
        imagesToolSkill.loadMedia(imageSkillLvl0);
        imagesToolSkill.loadMedia(imageSkillLvl1);
        
        IMediaListing imagesToolWeapon = mediaListingFactory.getMediaListing(0);
        IMediaElement imageToolPreview= mediaElementFactory.getTool(0);
        imageToolPreview.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\Weapon\\Stick\\stickPREVIEW.png");
        IMediaElement imageToolLvl0= mediaElementFactory.getTool(0);
        imageToolLvl0.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\Weapon\\Stick\\stickLevel1.png");
        IMediaElement imageToolLvl1= mediaElementFactory.getTool(0);
        imageToolLvl1.setPath("C:\\Users\\Marvin Armando\\Documents\\NetBeansProjects\\Diseño\\Proyecto\\CharacterCreationComponent\\src\\Images\\Character\\Weapon\\Stick\\stickLevel2.png");
        imagesToolWeapon.loadMedia(imageToolPreview);
        imagesToolWeapon.loadMedia(imageToolLvl0);
        imagesToolWeapon.loadMedia(imageToolLvl1);
        
        IToolListing toolListingCharacter = toolListingFactory.getToolListing(0);
        ITool toolSkill = toolFactory.getTool(0);
        
        ITool toolWeapon = toolFactory.getTool(0);
        
        ICharacterListing characterListing = characterListingFactory.getCharacterListing(0);
        IBuilder character = characterFactory.getCharacterBuilder();
        
        
        
        Skill tool = 
        
        
        
        imagesCharacter.loadMedia("CharacterWarrior", fileCharacter);
        imagesCharacter.loadMedia("CharacterWarrior", fileCharacter2);
        imagesCharacter.loadMedia("CharacterWarrior", fileCharacter3);
        imagesCharacter.loadMedia("CharacterWarrior", fileCharacter4);
        imagesToolSkill.loadMedia("WeaponPreview", fileWeapon);
        imagesToolSkill.loadMedia("WeaponLevel1", fileWeapon2);
        imagesToolSkill.loadMedia("WeaponLevel2", fileWeapon3);
        imagesToolWeapon.loadMedia("SkillPreview", fileSkill);
        imagesToolWeapon.loadMedia("SkillLevel1", fileSkill2);
        imagesToolWeapon.loadMedia("SkillLevel2", fileSkill3);

        tool.setMedia(images);
        //System.out.println(tool.getToString());
        //System.out.println(images.getImages().get(0).getPath());
        prueba.addTool(tool);

        Weapon tool2 = new Weapon(5, "RompeCulos", 100, 50, 10, 1, 2, 2, 1);
        tool2.setMedia(images2);
        //System.out.println(tool2.getToString());
        //System.out.println(images2.getImages().get(0).getPath());
        prueba.addTool(tool2);
        character = new Warrior("Prueba", 100, 50, prueba, 10, 10, 10, 10, 10, 10, imagesCharacter);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSelectCreationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSelectCreationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSelectCreationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSelectCreationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSelectCreationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newCharacterButton;
    private javax.swing.JButton templatesButton;
    // End of variables declaration//GEN-END:variables
}
